"""
validate_totals.py
CloseReport — 06.TOOLS

Compares aggregated totals from movements.csv (generated by ETL)
against the frozen reference Excel (2026_Mayo__2_.xlsx / Bases sheet).

Usage:
    python 06.TOOLS/validate_totals.py

Output:
    PASS: all totals match within 4-decimal tolerance
    FAIL: list of mismatches with entity / month / category / expected / got / delta

Precision rule: 4 decimal places fixed (DEC-003).
Reference rule: frozen Excel is the benchmark (DEC-004).
"""

import sys
from pathlib import Path
from decimal import Decimal, ROUND_HALF_UP

import pandas as pd

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parents[1]
MOVEMENTS_CSV = ROOT / "03.DATA" / "staging" / "movements.csv"
REFERENCE_XLSX = ROOT / "03.DATA" / "raw" / "2026_Mayo__2_.xlsx"
REFERENCE_SHEET = "Bases"
TOLERANCE = Decimal("0.0001")   # max allowed delta per cell

# Columns in movements.csv used for aggregation
GROUP_COLS = ["entity", "year", "month", "category"]
VALUE_COL  = "amount_uf"

# Columns in Bases used for the same aggregation
REF_ENTITY_COL   = "Empresa"
REF_YEAR_COL     = "Año"
REF_MONTH_COL    = "Mes"
REF_CATEGORY_COL = "Detalle2"
REF_VALUE_COL    = "UF"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def round4(value) -> Decimal:
    """Round to 4 decimal places using ROUND_HALF_UP."""
    return Decimal(str(value)).quantize(Decimal("0.0001"), rounding=ROUND_HALF_UP)


def load_movements() -> pd.DataFrame:
    if not MOVEMENTS_CSV.exists():
        print(f"[ERROR] movements.csv not found: {MOVEMENTS_CSV}")
        print("        Run load_movements.py first.")
        sys.exit(1)
    df = pd.read_csv(MOVEMENTS_CSV, dtype=str)
    df[VALUE_COL] = pd.to_numeric(df[VALUE_COL], errors="coerce").fillna(0)
    df["year"]  = pd.to_numeric(df["year"],  errors="coerce").astype("Int64")
    df["month"] = pd.to_numeric(df["month"], errors="coerce").astype("Int64")
    return df


def load_reference() -> pd.DataFrame:
    if not REFERENCE_XLSX.exists():
        print(f"[ERROR] Reference Excel not found: {REFERENCE_XLSX}")
        print("        Copy 2026_Mayo__2_.xlsx to 03.DATA/raw/")
        sys.exit(1)
    df = pd.read_excel(
        REFERENCE_XLSX,
        sheet_name=REFERENCE_SHEET,
        dtype=str,
        engine="openpyxl",
    )
    # Rename to match movements columns
    df = df.rename(columns={
        REF_ENTITY_COL:   "entity",
        REF_YEAR_COL:     "year",
        REF_MONTH_COL:    "month",
        REF_CATEGORY_COL: "category",
        REF_VALUE_COL:    "amount_uf",
    })
    df["amount_uf"] = pd.to_numeric(df["amount_uf"], errors="coerce").fillna(0)
    df["year"]  = pd.to_numeric(df["year"],  errors="coerce").astype("Int64")
    df["month"] = pd.to_numeric(df["month"], errors="coerce").astype("Int64")
    return df


def aggregate(df: pd.DataFrame) -> pd.DataFrame:
    """Sum amount_uf grouped by entity/year/month/category."""
    agg = (
        df.groupby(GROUP_COLS, dropna=False)[VALUE_COL]
        .sum()
        .reset_index()
    )
    agg[VALUE_COL] = agg[VALUE_COL].apply(round4)
    return agg


# ---------------------------------------------------------------------------
# Main comparison
# ---------------------------------------------------------------------------

def compare(csv_agg: pd.DataFrame, ref_agg: pd.DataFrame) -> list[dict]:
    """
    Join on GROUP_COLS, compare amount_uf values.
    Returns list of mismatches (empty = all pass).
    """
    merged = csv_agg.merge(
        ref_agg,
        on=GROUP_COLS,
        how="outer",
        suffixes=("_csv", "_ref"),
    )

    mismatches = []
    for _, row in merged.iterrows():
        csv_val = round4(row.get(f"{VALUE_COL}_csv", 0) or 0)
        ref_val = round4(row.get(f"{VALUE_COL}_ref", 0) or 0)
        delta = abs(csv_val - ref_val)
        if delta > TOLERANCE:
            mismatches.append({
                "entity":   row["entity"],
                "year":     row["year"],
                "month":    row["month"],
                "category": row["category"],
                "expected": float(ref_val),
                "got":      float(csv_val),
                "delta":    float(delta),
            })
    return mismatches


def main():
    print("=" * 60)
    print("CloseReport — validate_totals.py")
    print("=" * 60)

    print(f"\n[1/3] Loading movements.csv ...")
    csv_df = load_movements()
    csv_agg = aggregate(csv_df)
    print(f"      {len(csv_df):,} rows → {len(csv_agg):,} aggregated groups")

    print(f"\n[2/3] Loading reference Excel (Bases sheet) ...")
    ref_df = load_reference()
    ref_agg = aggregate(ref_df)
    print(f"      {len(ref_df):,} rows → {len(ref_agg):,} aggregated groups")

    print(f"\n[3/3] Comparing totals (tolerance: {TOLERANCE}) ...")
    mismatches = compare(csv_agg, ref_agg)

    print()
    if not mismatches:
        print("  ✓  PASS — all totals match within 4-decimal tolerance")
        print("  ✓  DELIVERABLE gate: OK to proceed to Power Query setup")
        sys.exit(0)
    else:
        print(f"  ✗  FAIL — {len(mismatches)} mismatch(es) found:\n")
        print(f"  {'ENTITY':<35} {'YEAR':>4} {'MO':>2} {'CATEGORY':<25} "
              f"{'EXPECTED':>12} {'GOT':>12} {'DELTA':>10}")
        print("  " + "-" * 110)
        for m in mismatches:
            print(
                f"  {str(m['entity']):<35} {str(m['year']):>4} {str(m['month']):>2} "
                f"  {str(m['category']):<25} {m['expected']:>12.4f} "
                f"{m['got']:>12.4f} {m['delta']:>10.4f}"
            )
        print()
        print("  Action: fix ETL, re-run load_movements.py, then re-validate.")
        sys.exit(1)


if __name__ == "__main__":
    main()
